apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-test
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
      - name: kubernetest-test
        image: theodorusyoga/kubernetes-test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        env:
          - name: NODE_ENV
            value: production
          - name: MYSQL_DATABASE
            value: kubernetes-test
          - name: MYSQL_PASSWORD
            value: mypass
          - name: MYSQL_HOST
            value: kubsql-service