apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubsql
  labels:
    app: kubernetes-test
spec:
  selector:
    matchLabels:
      app: kubernetes-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
      - image: mysql:8.0
        name: kubsql
        ports:
          - containerPort: 3306
            name: kubsql
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
              claimName: mysql-pv-claim
